Add search screen, fix PR.
Artem-Mushtakov/Apple-Music pull request #13
Opened 2021-12-17 20:53 UTC by Artem-Mushtakov

2021-12-23 06:16 UTC, mishapushka commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryCell.swift
> +            .padding(.trailing, 8)
нужно будет числа все в енамы запихать)) чтобы в коде не было цифр)

2021-12-23 06:16 UTC, mishapushka commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryView.swift
> +                        .padding(.trailing, 90)
в каждой вьюхе это сделать)) чтобы потом на собесе мог показать этот проект и тебе сказали что ты капитальный красавчик)

2022-01-05 09:32 UTC, nskazakov requested changes

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Player/PlayerView.swift
> +                .frame(width: expand ? Metric.widthFrameCapsule : Metric.anotherParametr, height: expand ? Metric.heightFrameCapsule : Metric.anotherParametr)
какая-то длинная строка получается

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Player/PlayerView.swift
> +    var animation: Namespace.ID
а это зачем?:)

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryCell.swift
> +    var rows  = [GridItem(.flexible())]
два пробела

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryCell.swift
> +                                .frame(width: 180, height: 180)
а почему тут числа не вынес в енамы? Раньше ж выносил (в структурах выше))))

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryView.swift
> +struct SearchCategoryView: View {
здесь тоже магические числа в енам

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchViewUIKit/CellMyAlbums.swift
> +        self.contentView.addSubview(titleLabel)
а зачем тут `self`?

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchView/SearchView.swift
> +                    SearchViewIntegrationUiKit()
съехало выравнивание

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchView/SearchView.swift
> +        repeating:GridItem(.flexible(),spacing: Metric.columnsSpacing),
пробелов не хватает

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchView/SearchResult/SearchResultView.swift
> +                    switch didTapLeft {
чего? Первый раз вижу switch для Bool
убери пж)))

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchView/SearchResult/SearchResultView.swift
> +                    switch didTapLeft {
if - else  же есть

2022-01-05 09:32 UTC, nskazakov commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryBanner.swift
> +struct SearchCategoryBanner: View {
Все магические числа в enum

2022-01-05 17:28 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Player/PlayerView.swift
> +    var animation: Namespace.ID
Для ползунков громкости и времени)

2022-01-05 17:30 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryCell.swift
> +                                .frame(width: 180, height: 180)
Странно в локальном репозитории в енамах у меня

2022-01-05 17:34 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Search screen/SearchViewUIKit/CellMyAlbums.swift
> +        self.contentView.addSubview(titleLabel)
Что бы был 😀, когда писал этот код, был молод и глуп, не знаю зачем тут self использовал(код взял с предыдущих дз) и походу при его использовании в этой дз применил принцип "работает не трогай" 😀 Убрал)

2022-01-05 17:36 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Search screen/SearchView/SearchResult/SearchResultView.swift
> +                    switch didTapLeft {
Я просто знал что ты не разу не видел switch для bool, вот решил показать что так тоже можно🤣

2022-01-05 17:39 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryBanner.swift
> +struct SearchCategoryBanner: View {
Тоже в локальном все в енамах

2022-01-05 17:39 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Search screen/SearchView/SearchView.swift
> +        repeating:GridItem(.flexible(),spacing: Metric.columnsSpacing),
✅

2022-01-05 17:40 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Search screen/SearchView/SearchView.swift
> +                    SearchViewIntegrationUiKit()
✅

2022-01-05 17:40 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryView.swift
> +struct SearchCategoryView: View {
Тоже в локальном все в енамах

2022-01-05 17:40 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Search screen/SearchCategory/SearchCategoryCell.swift
> +    var rows  = [GridItem(.flexible())]
✅

2022-01-05 17:40 UTC, Artem-Mushtakov commented on Apple_Music/View/Modules/Player/PlayerView.swift
> +                .frame(width: expand ? Metric.widthFrameCapsule : Metric.anotherParametr, height: expand ? Metric.heightFrameCapsule : Metric.anotherParametr)
✅

2022-01-18 02:44 UTC, nskazakov approved these changes
Каиф

2022-08-24 21:18 UTC, merged